import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import InfoHeader from "@/components/InfoHeader";
import Navbar from "@/components/Navbar";
import MobileNav from "@/components/MobileNav";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <main className="flex flex-col">
          <section className="flex h-full flex-1 justify-between">
            <InfoHeader />
            <MobileNav />
          </section>
          <Navbar />
          
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
